version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis-database
    ports:
      - '6379:6379'
    networks:
      - 3containers

  ml-app:
    build: 
      context: ./app
      dockerfile: Dockerfile.app    
    container_name: sentence-similarity-app
    ports:
      - '8501:8501'
    depends_on:
      - redis
    networks:
      - 3containers
  

  datafile:
    build: 
      context: ./data
      dockerfile: Dockerfile.data 
    container_name: datacontainer
    depends_on:
      - redis
    networks:
      - 3containers
    
networks:
  3containers:
    driver: bridge

